import type { InjectionKey, Ref } from 'vue';
import type { ConfigProviderProps } from 'element-plus';
import type { TablePageContext } from 'element-plus-x/es/components/table-page';
import type { ConfigProviderV2Context } from '../constants';
export declare const getCfgOptions: <T extends Partial<ConfigProviderV2Context & ConfigProviderProps>>(options: T) => {
    epCfg: Record<string, any>;
    epxCfg: Record<string, any>;
};
export declare const getDefaultTablePageConfig: () => {
    pagination: {
        defaultPageSize: number;
        pageSizes: number[];
        layout: string;
        background: boolean;
        showRecord: boolean;
        showTotal: boolean;
    };
    config: {
        currentPage: string;
        pageSize: string;
        total: string;
    };
};
export declare const tablePageContextKey: InjectionKey<Ref<TablePageContext>>;
export declare const useTablePageConfig: () => {
    tablePageConfig: Ref<TablePageContext, TablePageContext> | import("vue").ComputedRef<TablePageContext>;
};
export declare const globalConfig: Ref<{
    readonly tablePage?: {
        pagination: {
            readonly teleported?: import("element-plus/es/utils").EpPropMergeType<BooleanConstructor, unknown, unknown> | undefined;
            readonly small?: boolean | undefined;
            readonly pageSizes?: number[] | undefined;
            readonly pagerCount?: number | undefined;
            readonly layout?: string | undefined;
            readonly popperClass?: string | undefined;
            readonly prevText?: string | undefined;
            readonly nextText?: string | undefined;
            readonly background?: boolean | undefined;
            readonly disabled?: boolean | undefined;
            readonly hideOnSinglePage?: boolean | undefined;
            readonly size?: import("element-plus/es/utils").EpPropMergeType<StringConstructor, "" | "small" | "default" | "large", never> | undefined;
            readonly total?: number | undefined;
            readonly pageSize?: number | undefined;
            defaultPageSize?: number | undefined;
            readonly pageCount?: number | undefined;
            readonly currentPage?: number | undefined;
            readonly defaultCurrentPage?: number | undefined;
            readonly prevIcon?: string | import("vue").FunctionalComponent<any, {}, any, {}> | {
                new (...args: any[]): any;
                __isFragment?: never;
                __isTeleport?: never;
                __isSuspense?: never;
            } | {
                [x: string]: any;
                setup?: ((this: void, props: import("@vue/shared").LooseRequired<any>, ctx: {
                    attrs: {
                        [x: string]: unknown;
                    };
                    slots: Readonly<{
                        [name: string]: import("vue").Slot<any> | undefined;
                    }>;
                    emit: ((event: unknown, ...args: any[]) => void) | ((event: string, ...args: any[]) => void);
                    expose: <Exposed extends Record<string, any> = Record<string, any>>(exposed?: Exposed) => void;
                }) => any) | undefined;
                name?: string | undefined;
                template?: (string | object) | undefined;
                render?: Function | undefined;
                components?: Record<string, import("vue").Component<any, any, any, import("vue").ComputedOptions, import("vue").MethodOptions, {}, any>> | undefined;
                directives?: Record<string, import("vue").Directive<any, any, string, string>> | undefined;
                inheritAttrs?: boolean | undefined;
                emits?: any;
                slots?: {} | undefined;
                expose?: string[] | undefined;
                serverPrefetch?: (() => void | Promise<any>) | undefined;
                compilerOptions?: {
                    isCustomElement?: ((tag: string) => boolean) | undefined;
                    whitespace?: ("preserve" | "condense") | undefined;
                    comments?: boolean | undefined;
                    delimiters?: [string, string] | undefined;
                } | undefined;
                call?: ((this: unknown, ...args: unknown[]) => never) | undefined;
                __isFragment?: never | undefined;
                __isTeleport?: never | undefined;
                __isSuspense?: never | undefined;
                __defaults?: {} | undefined;
                compatConfig?: {
                    GLOBAL_MOUNT?: boolean | "suppress-warning" | undefined;
                    GLOBAL_MOUNT_CONTAINER?: boolean | "suppress-warning" | undefined;
                    GLOBAL_EXTEND?: boolean | "suppress-warning" | undefined;
                    GLOBAL_PROTOTYPE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_SET?: boolean | "suppress-warning" | undefined;
                    GLOBAL_DELETE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_OBSERVABLE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_PRIVATE_UTIL?: boolean | "suppress-warning" | undefined;
                    CONFIG_SILENT?: boolean | "suppress-warning" | undefined;
                    CONFIG_DEVTOOLS?: boolean | "suppress-warning" | undefined;
                    CONFIG_KEY_CODES?: boolean | "suppress-warning" | undefined;
                    CONFIG_PRODUCTION_TIP?: boolean | "suppress-warning" | undefined;
                    CONFIG_IGNORED_ELEMENTS?: boolean | "suppress-warning" | undefined;
                    CONFIG_WHITESPACE?: boolean | "suppress-warning" | undefined;
                    CONFIG_OPTION_MERGE_STRATS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_SET?: boolean | "suppress-warning" | undefined;
                    INSTANCE_DELETE?: boolean | "suppress-warning" | undefined;
                    INSTANCE_DESTROY?: boolean | "suppress-warning" | undefined;
                    INSTANCE_EVENT_EMITTER?: boolean | "suppress-warning" | undefined;
                    INSTANCE_EVENT_HOOKS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_CHILDREN?: boolean | "suppress-warning" | undefined;
                    INSTANCE_LISTENERS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_SCOPED_SLOTS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_ATTRS_CLASS_STYLE?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DATA_FN?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DATA_MERGE?: boolean | "suppress-warning" | undefined;
                    OPTIONS_BEFORE_DESTROY?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DESTROYED?: boolean | "suppress-warning" | undefined;
                    WATCH_ARRAY?: boolean | "suppress-warning" | undefined;
                    PROPS_DEFAULT_THIS?: boolean | "suppress-warning" | undefined;
                    V_ON_KEYCODE_MODIFIER?: boolean | "suppress-warning" | undefined;
                    CUSTOM_DIR?: boolean | "suppress-warning" | undefined;
                    ATTR_FALSE_VALUE?: boolean | "suppress-warning" | undefined;
                    ATTR_ENUMERATED_COERCION?: boolean | "suppress-warning" | undefined;
                    TRANSITION_CLASSES?: boolean | "suppress-warning" | undefined;
                    TRANSITION_GROUP_ROOT?: boolean | "suppress-warning" | undefined;
                    COMPONENT_ASYNC?: boolean | "suppress-warning" | undefined;
                    COMPONENT_FUNCTIONAL?: boolean | "suppress-warning" | undefined;
                    COMPONENT_V_MODEL?: boolean | "suppress-warning" | undefined;
                    RENDER_FUNCTION?: boolean | "suppress-warning" | undefined;
                    FILTERS?: boolean | "suppress-warning" | undefined;
                    PRIVATE_APIS?: boolean | "suppress-warning" | undefined;
                    MODE?: (2 | 3 | ((comp: import("vue").Component | null) => 2 | 3)) | undefined;
                } | undefined;
                data?: ((this: any, vm: any) => any) | undefined;
                computed?: import("vue").ComputedOptions | undefined;
                methods?: import("vue").MethodOptions | undefined;
                watch?: {
                    [x: string]: (string | import("vue").WatchCallback | ({
                        handler: import("vue").WatchCallback | string;
                    } & import("vue").WatchOptions<boolean>)) | (string | import("vue").WatchCallback | ({
                        handler: import("vue").WatchCallback | string;
                    } & import("vue").WatchOptions<boolean>))[];
                } | undefined;
                provide?: import("vue").ComponentProvideOptions | undefined;
                inject?: {} | string[] | undefined;
                filters?: Record<string, Function> | undefined;
                mixins?: any[] | undefined;
                extends?: any;
                beforeCreate?: (() => void) | undefined;
                created?: (() => void) | undefined;
                beforeMount?: (() => void) | undefined;
                mounted?: (() => void) | undefined;
                beforeUpdate?: (() => void) | undefined;
                updated?: (() => void) | undefined;
                activated?: (() => void) | undefined;
                deactivated?: (() => void) | undefined;
                beforeDestroy?: (() => void) | undefined;
                beforeUnmount?: (() => void) | undefined;
                destroyed?: (() => void) | undefined;
                unmounted?: (() => void) | undefined;
                renderTracked?: ((e: import("vue").DebuggerEvent) => void) | undefined;
                renderTriggered?: ((e: import("vue").DebuggerEvent) => void) | undefined;
                errorCaptured?: ((err: unknown, instance: import("vue").ComponentPublicInstance | null, info: string) => boolean | void) | undefined;
                delimiters?: [string, string] | undefined;
                __differentiator?: string | number | symbol | undefined;
                __isBuiltIn?: boolean | undefined;
                __file?: string | undefined;
                __name?: string | undefined;
                beforeRouteEnter?: (import("vue-router").TypesConfig extends Record<"beforeRouteEnter", infer T> ? T : import("vue-router").NavigationGuardWithThis<undefined>) | undefined;
                beforeRouteUpdate?: (import("vue-router").TypesConfig extends Record<"beforeRouteUpdate", infer T> ? T : import("vue-router").NavigationGuard) | undefined;
                beforeRouteLeave?: (import("vue-router").TypesConfig extends Record<"beforeRouteLeave", infer T> ? T : import("vue-router").NavigationGuard) | undefined;
            } | undefined;
            readonly nextIcon?: string | import("vue").FunctionalComponent<any, {}, any, {}> | {
                new (...args: any[]): any;
                __isFragment?: never;
                __isTeleport?: never;
                __isSuspense?: never;
            } | {
                [x: string]: any;
                setup?: ((this: void, props: import("@vue/shared").LooseRequired<any>, ctx: {
                    attrs: {
                        [x: string]: unknown;
                    };
                    slots: Readonly<{
                        [name: string]: import("vue").Slot<any> | undefined;
                    }>;
                    emit: ((event: unknown, ...args: any[]) => void) | ((event: string, ...args: any[]) => void);
                    expose: <Exposed extends Record<string, any> = Record<string, any>>(exposed?: Exposed) => void;
                }) => any) | undefined;
                name?: string | undefined;
                template?: (string | object) | undefined;
                render?: Function | undefined;
                components?: Record<string, import("vue").Component<any, any, any, import("vue").ComputedOptions, import("vue").MethodOptions, {}, any>> | undefined;
                directives?: Record<string, import("vue").Directive<any, any, string, string>> | undefined;
                inheritAttrs?: boolean | undefined;
                emits?: any;
                slots?: {} | undefined;
                expose?: string[] | undefined;
                serverPrefetch?: (() => void | Promise<any>) | undefined;
                compilerOptions?: {
                    isCustomElement?: ((tag: string) => boolean) | undefined;
                    whitespace?: ("preserve" | "condense") | undefined;
                    comments?: boolean | undefined;
                    delimiters?: [string, string] | undefined;
                } | undefined;
                call?: ((this: unknown, ...args: unknown[]) => never) | undefined;
                __isFragment?: never | undefined;
                __isTeleport?: never | undefined;
                __isSuspense?: never | undefined;
                __defaults?: {} | undefined;
                compatConfig?: {
                    GLOBAL_MOUNT?: boolean | "suppress-warning" | undefined;
                    GLOBAL_MOUNT_CONTAINER?: boolean | "suppress-warning" | undefined;
                    GLOBAL_EXTEND?: boolean | "suppress-warning" | undefined;
                    GLOBAL_PROTOTYPE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_SET?: boolean | "suppress-warning" | undefined;
                    GLOBAL_DELETE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_OBSERVABLE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_PRIVATE_UTIL?: boolean | "suppress-warning" | undefined;
                    CONFIG_SILENT?: boolean | "suppress-warning" | undefined;
                    CONFIG_DEVTOOLS?: boolean | "suppress-warning" | undefined;
                    CONFIG_KEY_CODES?: boolean | "suppress-warning" | undefined;
                    CONFIG_PRODUCTION_TIP?: boolean | "suppress-warning" | undefined;
                    CONFIG_IGNORED_ELEMENTS?: boolean | "suppress-warning" | undefined;
                    CONFIG_WHITESPACE?: boolean | "suppress-warning" | undefined;
                    CONFIG_OPTION_MERGE_STRATS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_SET?: boolean | "suppress-warning" | undefined;
                    INSTANCE_DELETE?: boolean | "suppress-warning" | undefined;
                    INSTANCE_DESTROY?: boolean | "suppress-warning" | undefined;
                    INSTANCE_EVENT_EMITTER?: boolean | "suppress-warning" | undefined;
                    INSTANCE_EVENT_HOOKS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_CHILDREN?: boolean | "suppress-warning" | undefined;
                    INSTANCE_LISTENERS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_SCOPED_SLOTS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_ATTRS_CLASS_STYLE?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DATA_FN?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DATA_MERGE?: boolean | "suppress-warning" | undefined;
                    OPTIONS_BEFORE_DESTROY?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DESTROYED?: boolean | "suppress-warning" | undefined;
                    WATCH_ARRAY?: boolean | "suppress-warning" | undefined;
                    PROPS_DEFAULT_THIS?: boolean | "suppress-warning" | undefined;
                    V_ON_KEYCODE_MODIFIER?: boolean | "suppress-warning" | undefined;
                    CUSTOM_DIR?: boolean | "suppress-warning" | undefined;
                    ATTR_FALSE_VALUE?: boolean | "suppress-warning" | undefined;
                    ATTR_ENUMERATED_COERCION?: boolean | "suppress-warning" | undefined;
                    TRANSITION_CLASSES?: boolean | "suppress-warning" | undefined;
                    TRANSITION_GROUP_ROOT?: boolean | "suppress-warning" | undefined;
                    COMPONENT_ASYNC?: boolean | "suppress-warning" | undefined;
                    COMPONENT_FUNCTIONAL?: boolean | "suppress-warning" | undefined;
                    COMPONENT_V_MODEL?: boolean | "suppress-warning" | undefined;
                    RENDER_FUNCTION?: boolean | "suppress-warning" | undefined;
                    FILTERS?: boolean | "suppress-warning" | undefined;
                    PRIVATE_APIS?: boolean | "suppress-warning" | undefined;
                    MODE?: (2 | 3 | ((comp: import("vue").Component | null) => 2 | 3)) | undefined;
                } | undefined;
                data?: ((this: any, vm: any) => any) | undefined;
                computed?: import("vue").ComputedOptions | undefined;
                methods?: import("vue").MethodOptions | undefined;
                watch?: {
                    [x: string]: (string | import("vue").WatchCallback | ({
                        handler: import("vue").WatchCallback | string;
                    } & import("vue").WatchOptions<boolean>)) | (string | import("vue").WatchCallback | ({
                        handler: import("vue").WatchCallback | string;
                    } & import("vue").WatchOptions<boolean>))[];
                } | undefined;
                provide?: import("vue").ComponentProvideOptions | undefined;
                inject?: {} | string[] | undefined;
                filters?: Record<string, Function> | undefined;
                mixins?: any[] | undefined;
                extends?: any;
                beforeCreate?: (() => void) | undefined;
                created?: (() => void) | undefined;
                beforeMount?: (() => void) | undefined;
                mounted?: (() => void) | undefined;
                beforeUpdate?: (() => void) | undefined;
                updated?: (() => void) | undefined;
                activated?: (() => void) | undefined;
                deactivated?: (() => void) | undefined;
                beforeDestroy?: (() => void) | undefined;
                beforeUnmount?: (() => void) | undefined;
                destroyed?: (() => void) | undefined;
                unmounted?: (() => void) | undefined;
                renderTracked?: ((e: import("vue").DebuggerEvent) => void) | undefined;
                renderTriggered?: ((e: import("vue").DebuggerEvent) => void) | undefined;
                errorCaptured?: ((err: unknown, instance: import("vue").ComponentPublicInstance | null, info: string) => boolean | void) | undefined;
                delimiters?: [string, string] | undefined;
                __differentiator?: string | number | symbol | undefined;
                __isBuiltIn?: boolean | undefined;
                __file?: string | undefined;
                __name?: string | undefined;
                beforeRouteEnter?: (import("vue-router").TypesConfig extends Record<"beforeRouteEnter", infer T> ? T : import("vue-router").NavigationGuardWithThis<undefined>) | undefined;
                beforeRouteUpdate?: (import("vue-router").TypesConfig extends Record<"beforeRouteUpdate", infer T> ? T : import("vue-router").NavigationGuard) | undefined;
                beforeRouteLeave?: (import("vue-router").TypesConfig extends Record<"beforeRouteLeave", infer T> ? T : import("vue-router").NavigationGuard) | undefined;
            } | undefined;
            readonly appendSizeTo?: string | undefined;
            showRecord?: boolean | undefined;
            showTotal?: boolean | undefined;
        };
        config?: {
            currentPage?: string | undefined;
            pageSize?: string | undefined;
            total?: string | undefined;
        } | undefined;
    } | undefined;
}, Partial<import("../config-provider-v2-props").ConfigProviderV2Props> | {
    readonly tablePage?: {
        pagination: {
            readonly teleported?: import("element-plus/es/utils").EpPropMergeType<BooleanConstructor, unknown, unknown> | undefined;
            readonly small?: boolean | undefined;
            readonly pageSizes?: number[] | undefined;
            readonly pagerCount?: number | undefined;
            readonly layout?: string | undefined;
            readonly popperClass?: string | undefined;
            readonly prevText?: string | undefined;
            readonly nextText?: string | undefined;
            readonly background?: boolean | undefined;
            readonly disabled?: boolean | undefined;
            readonly hideOnSinglePage?: boolean | undefined;
            readonly size?: import("element-plus/es/utils").EpPropMergeType<StringConstructor, "" | "small" | "default" | "large", never> | undefined;
            readonly total?: number | undefined;
            readonly pageSize?: number | undefined;
            defaultPageSize?: number | undefined;
            readonly pageCount?: number | undefined;
            readonly currentPage?: number | undefined;
            readonly defaultCurrentPage?: number | undefined;
            readonly prevIcon?: string | import("vue").FunctionalComponent<any, {}, any, {}> | {
                new (...args: any[]): any;
                __isFragment?: never;
                __isTeleport?: never;
                __isSuspense?: never;
            } | {
                [x: string]: any;
                setup?: ((this: void, props: import("@vue/shared").LooseRequired<any>, ctx: {
                    attrs: {
                        [x: string]: unknown;
                    };
                    slots: Readonly<{
                        [name: string]: import("vue").Slot<any> | undefined;
                    }>;
                    emit: ((event: unknown, ...args: any[]) => void) | ((event: string, ...args: any[]) => void);
                    expose: <Exposed extends Record<string, any> = Record<string, any>>(exposed?: Exposed) => void;
                }) => any) | undefined;
                name?: string | undefined;
                template?: (string | object) | undefined;
                render?: Function | undefined;
                components?: Record<string, import("vue").Component<any, any, any, import("vue").ComputedOptions, import("vue").MethodOptions, {}, any>> | undefined;
                directives?: Record<string, import("vue").Directive<any, any, string, string>> | undefined;
                inheritAttrs?: boolean | undefined;
                emits?: any;
                slots?: {} | undefined;
                expose?: string[] | undefined;
                serverPrefetch?: (() => void | Promise<any>) | undefined;
                compilerOptions?: {
                    isCustomElement?: ((tag: string) => boolean) | undefined;
                    whitespace?: ("preserve" | "condense") | undefined;
                    comments?: boolean | undefined;
                    delimiters?: [string, string] | undefined;
                } | undefined;
                call?: ((this: unknown, ...args: unknown[]) => never) | undefined;
                __isFragment?: never | undefined;
                __isTeleport?: never | undefined;
                __isSuspense?: never | undefined;
                __defaults?: {} | undefined;
                compatConfig?: {
                    GLOBAL_MOUNT?: boolean | "suppress-warning" | undefined;
                    GLOBAL_MOUNT_CONTAINER?: boolean | "suppress-warning" | undefined;
                    GLOBAL_EXTEND?: boolean | "suppress-warning" | undefined;
                    GLOBAL_PROTOTYPE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_SET?: boolean | "suppress-warning" | undefined;
                    GLOBAL_DELETE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_OBSERVABLE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_PRIVATE_UTIL?: boolean | "suppress-warning" | undefined;
                    CONFIG_SILENT?: boolean | "suppress-warning" | undefined;
                    CONFIG_DEVTOOLS?: boolean | "suppress-warning" | undefined;
                    CONFIG_KEY_CODES?: boolean | "suppress-warning" | undefined;
                    CONFIG_PRODUCTION_TIP?: boolean | "suppress-warning" | undefined;
                    CONFIG_IGNORED_ELEMENTS?: boolean | "suppress-warning" | undefined;
                    CONFIG_WHITESPACE?: boolean | "suppress-warning" | undefined;
                    CONFIG_OPTION_MERGE_STRATS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_SET?: boolean | "suppress-warning" | undefined;
                    INSTANCE_DELETE?: boolean | "suppress-warning" | undefined;
                    INSTANCE_DESTROY?: boolean | "suppress-warning" | undefined;
                    INSTANCE_EVENT_EMITTER?: boolean | "suppress-warning" | undefined;
                    INSTANCE_EVENT_HOOKS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_CHILDREN?: boolean | "suppress-warning" | undefined;
                    INSTANCE_LISTENERS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_SCOPED_SLOTS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_ATTRS_CLASS_STYLE?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DATA_FN?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DATA_MERGE?: boolean | "suppress-warning" | undefined;
                    OPTIONS_BEFORE_DESTROY?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DESTROYED?: boolean | "suppress-warning" | undefined;
                    WATCH_ARRAY?: boolean | "suppress-warning" | undefined;
                    PROPS_DEFAULT_THIS?: boolean | "suppress-warning" | undefined;
                    V_ON_KEYCODE_MODIFIER?: boolean | "suppress-warning" | undefined;
                    CUSTOM_DIR?: boolean | "suppress-warning" | undefined;
                    ATTR_FALSE_VALUE?: boolean | "suppress-warning" | undefined;
                    ATTR_ENUMERATED_COERCION?: boolean | "suppress-warning" | undefined;
                    TRANSITION_CLASSES?: boolean | "suppress-warning" | undefined;
                    TRANSITION_GROUP_ROOT?: boolean | "suppress-warning" | undefined;
                    COMPONENT_ASYNC?: boolean | "suppress-warning" | undefined;
                    COMPONENT_FUNCTIONAL?: boolean | "suppress-warning" | undefined;
                    COMPONENT_V_MODEL?: boolean | "suppress-warning" | undefined;
                    RENDER_FUNCTION?: boolean | "suppress-warning" | undefined;
                    FILTERS?: boolean | "suppress-warning" | undefined;
                    PRIVATE_APIS?: boolean | "suppress-warning" | undefined;
                    MODE?: (2 | 3 | ((comp: import("vue").Component | null) => 2 | 3)) | undefined;
                } | undefined;
                data?: ((this: any, vm: any) => any) | undefined;
                computed?: import("vue").ComputedOptions | undefined;
                methods?: import("vue").MethodOptions | undefined;
                watch?: {
                    [x: string]: (string | import("vue").WatchCallback | ({
                        handler: import("vue").WatchCallback | string;
                    } & import("vue").WatchOptions<boolean>)) | (string | import("vue").WatchCallback | ({
                        handler: import("vue").WatchCallback | string;
                    } & import("vue").WatchOptions<boolean>))[];
                } | undefined;
                provide?: import("vue").ComponentProvideOptions | undefined;
                inject?: {} | string[] | undefined;
                filters?: Record<string, Function> | undefined;
                mixins?: any[] | undefined;
                extends?: any;
                beforeCreate?: (() => void) | undefined;
                created?: (() => void) | undefined;
                beforeMount?: (() => void) | undefined;
                mounted?: (() => void) | undefined;
                beforeUpdate?: (() => void) | undefined;
                updated?: (() => void) | undefined;
                activated?: (() => void) | undefined;
                deactivated?: (() => void) | undefined;
                beforeDestroy?: (() => void) | undefined;
                beforeUnmount?: (() => void) | undefined;
                destroyed?: (() => void) | undefined;
                unmounted?: (() => void) | undefined;
                renderTracked?: ((e: import("vue").DebuggerEvent) => void) | undefined;
                renderTriggered?: ((e: import("vue").DebuggerEvent) => void) | undefined;
                errorCaptured?: ((err: unknown, instance: import("vue").ComponentPublicInstance | null, info: string) => boolean | void) | undefined;
                delimiters?: [string, string] | undefined;
                __differentiator?: string | number | symbol | undefined;
                __isBuiltIn?: boolean | undefined;
                __file?: string | undefined;
                __name?: string | undefined;
                beforeRouteEnter?: (import("vue-router").TypesConfig extends Record<"beforeRouteEnter", infer T> ? T : import("vue-router").NavigationGuardWithThis<undefined>) | undefined;
                beforeRouteUpdate?: (import("vue-router").TypesConfig extends Record<"beforeRouteUpdate", infer T> ? T : import("vue-router").NavigationGuard) | undefined;
                beforeRouteLeave?: (import("vue-router").TypesConfig extends Record<"beforeRouteLeave", infer T> ? T : import("vue-router").NavigationGuard) | undefined;
            } | undefined;
            readonly nextIcon?: string | import("vue").FunctionalComponent<any, {}, any, {}> | {
                new (...args: any[]): any;
                __isFragment?: never;
                __isTeleport?: never;
                __isSuspense?: never;
            } | {
                [x: string]: any;
                setup?: ((this: void, props: import("@vue/shared").LooseRequired<any>, ctx: {
                    attrs: {
                        [x: string]: unknown;
                    };
                    slots: Readonly<{
                        [name: string]: import("vue").Slot<any> | undefined;
                    }>;
                    emit: ((event: unknown, ...args: any[]) => void) | ((event: string, ...args: any[]) => void);
                    expose: <Exposed extends Record<string, any> = Record<string, any>>(exposed?: Exposed) => void;
                }) => any) | undefined;
                name?: string | undefined;
                template?: (string | object) | undefined;
                render?: Function | undefined;
                components?: Record<string, import("vue").Component<any, any, any, import("vue").ComputedOptions, import("vue").MethodOptions, {}, any>> | undefined;
                directives?: Record<string, import("vue").Directive<any, any, string, string>> | undefined;
                inheritAttrs?: boolean | undefined;
                emits?: any;
                slots?: {} | undefined;
                expose?: string[] | undefined;
                serverPrefetch?: (() => void | Promise<any>) | undefined;
                compilerOptions?: {
                    isCustomElement?: ((tag: string) => boolean) | undefined;
                    whitespace?: ("preserve" | "condense") | undefined;
                    comments?: boolean | undefined;
                    delimiters?: [string, string] | undefined;
                } | undefined;
                call?: ((this: unknown, ...args: unknown[]) => never) | undefined;
                __isFragment?: never | undefined;
                __isTeleport?: never | undefined;
                __isSuspense?: never | undefined;
                __defaults?: {} | undefined;
                compatConfig?: {
                    GLOBAL_MOUNT?: boolean | "suppress-warning" | undefined;
                    GLOBAL_MOUNT_CONTAINER?: boolean | "suppress-warning" | undefined;
                    GLOBAL_EXTEND?: boolean | "suppress-warning" | undefined;
                    GLOBAL_PROTOTYPE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_SET?: boolean | "suppress-warning" | undefined;
                    GLOBAL_DELETE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_OBSERVABLE?: boolean | "suppress-warning" | undefined;
                    GLOBAL_PRIVATE_UTIL?: boolean | "suppress-warning" | undefined;
                    CONFIG_SILENT?: boolean | "suppress-warning" | undefined;
                    CONFIG_DEVTOOLS?: boolean | "suppress-warning" | undefined;
                    CONFIG_KEY_CODES?: boolean | "suppress-warning" | undefined;
                    CONFIG_PRODUCTION_TIP?: boolean | "suppress-warning" | undefined;
                    CONFIG_IGNORED_ELEMENTS?: boolean | "suppress-warning" | undefined;
                    CONFIG_WHITESPACE?: boolean | "suppress-warning" | undefined;
                    CONFIG_OPTION_MERGE_STRATS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_SET?: boolean | "suppress-warning" | undefined;
                    INSTANCE_DELETE?: boolean | "suppress-warning" | undefined;
                    INSTANCE_DESTROY?: boolean | "suppress-warning" | undefined;
                    INSTANCE_EVENT_EMITTER?: boolean | "suppress-warning" | undefined;
                    INSTANCE_EVENT_HOOKS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_CHILDREN?: boolean | "suppress-warning" | undefined;
                    INSTANCE_LISTENERS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_SCOPED_SLOTS?: boolean | "suppress-warning" | undefined;
                    INSTANCE_ATTRS_CLASS_STYLE?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DATA_FN?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DATA_MERGE?: boolean | "suppress-warning" | undefined;
                    OPTIONS_BEFORE_DESTROY?: boolean | "suppress-warning" | undefined;
                    OPTIONS_DESTROYED?: boolean | "suppress-warning" | undefined;
                    WATCH_ARRAY?: boolean | "suppress-warning" | undefined;
                    PROPS_DEFAULT_THIS?: boolean | "suppress-warning" | undefined;
                    V_ON_KEYCODE_MODIFIER?: boolean | "suppress-warning" | undefined;
                    CUSTOM_DIR?: boolean | "suppress-warning" | undefined;
                    ATTR_FALSE_VALUE?: boolean | "suppress-warning" | undefined;
                    ATTR_ENUMERATED_COERCION?: boolean | "suppress-warning" | undefined;
                    TRANSITION_CLASSES?: boolean | "suppress-warning" | undefined;
                    TRANSITION_GROUP_ROOT?: boolean | "suppress-warning" | undefined;
                    COMPONENT_ASYNC?: boolean | "suppress-warning" | undefined;
                    COMPONENT_FUNCTIONAL?: boolean | "suppress-warning" | undefined;
                    COMPONENT_V_MODEL?: boolean | "suppress-warning" | undefined;
                    RENDER_FUNCTION?: boolean | "suppress-warning" | undefined;
                    FILTERS?: boolean | "suppress-warning" | undefined;
                    PRIVATE_APIS?: boolean | "suppress-warning" | undefined;
                    MODE?: (2 | 3 | ((comp: import("vue").Component | null) => 2 | 3)) | undefined;
                } | undefined;
                data?: ((this: any, vm: any) => any) | undefined;
                computed?: import("vue").ComputedOptions | undefined;
                methods?: import("vue").MethodOptions | undefined;
                watch?: {
                    [x: string]: (string | import("vue").WatchCallback | ({
                        handler: import("vue").WatchCallback | string;
                    } & import("vue").WatchOptions<boolean>)) | (string | import("vue").WatchCallback | ({
                        handler: import("vue").WatchCallback | string;
                    } & import("vue").WatchOptions<boolean>))[];
                } | undefined;
                provide?: import("vue").ComponentProvideOptions | undefined;
                inject?: {} | string[] | undefined;
                filters?: Record<string, Function> | undefined;
                mixins?: any[] | undefined;
                extends?: any;
                beforeCreate?: (() => void) | undefined;
                created?: (() => void) | undefined;
                beforeMount?: (() => void) | undefined;
                mounted?: (() => void) | undefined;
                beforeUpdate?: (() => void) | undefined;
                updated?: (() => void) | undefined;
                activated?: (() => void) | undefined;
                deactivated?: (() => void) | undefined;
                beforeDestroy?: (() => void) | undefined;
                beforeUnmount?: (() => void) | undefined;
                destroyed?: (() => void) | undefined;
                unmounted?: (() => void) | undefined;
                renderTracked?: ((e: import("vue").DebuggerEvent) => void) | undefined;
                renderTriggered?: ((e: import("vue").DebuggerEvent) => void) | undefined;
                errorCaptured?: ((err: unknown, instance: import("vue").ComponentPublicInstance | null, info: string) => boolean | void) | undefined;
                delimiters?: [string, string] | undefined;
                __differentiator?: string | number | symbol | undefined;
                __isBuiltIn?: boolean | undefined;
                __file?: string | undefined;
                __name?: string | undefined;
                beforeRouteEnter?: (import("vue-router").TypesConfig extends Record<"beforeRouteEnter", infer T> ? T : import("vue-router").NavigationGuardWithThis<undefined>) | undefined;
                beforeRouteUpdate?: (import("vue-router").TypesConfig extends Record<"beforeRouteUpdate", infer T> ? T : import("vue-router").NavigationGuard) | undefined;
                beforeRouteLeave?: (import("vue-router").TypesConfig extends Record<"beforeRouteLeave", infer T> ? T : import("vue-router").NavigationGuard) | undefined;
            } | undefined;
            readonly appendSizeTo?: string | undefined;
            showRecord?: boolean | undefined;
            showTotal?: boolean | undefined;
        };
        config?: {
            currentPage?: string | undefined;
            pageSize?: string | undefined;
            total?: string | undefined;
        } | undefined;
    } | undefined;
}>;
export declare const mergeGlobalConfig: (cfg: ConfigProviderV2Context) => void;
