import Emoji from './src/index.vue';
import Emoticon from './src/emoticon.vue';
import FontEmoticon from './src/font-emoticon.vue';
import type { SFCWithInstall } from 'element-plus-x/es/utils';
export declare const ElEmoji: SFCWithInstall<typeof Emoji>;
export default ElEmoji;
export declare const ElEmoticon: SFCWithInstall<typeof Emoticon>;
export declare const ElFontEmoticon: SFCWithInstall<typeof FontEmoticon>;
export * from './src/emoji';
export * from './src/helper';
export * from './src/trie';
export type { EmojiInstance } from './src/instance';
